# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-23 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('cleaners', '0002_auto_20170523_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaner',
            name='cities',
            field=models.ManyToManyField(to='cities.City'),
        ),
    ]
